begin;

create table if not exists public.stock_hist_cache (
  symbol text not null,
  adjust text not null,
  date date not null,
  open double precision,
  high double precision,
  low double precision,
  close double precision,
  volume double precision,
  amount double precision,
  pct_chg double precision,
  turnover_rate double precision,
  amplitude double precision,
  updated_at timestamptz not null default now(),
  primary key (symbol, adjust, date)
);

create index if not exists idx_stock_hist_cache_symbol_adjust_date_desc
  on public.stock_hist_cache (symbol, adjust, date desc);


create table if not exists public.market_signal_daily (
  trade_date date not null,
  market text not null default 'cn',
  benchmark_regime text,
  main_index_code text,
  main_index_close double precision,
  main_index_ma50 double precision,
  main_index_ma200 double precision,
  main_index_recent3_cum_pct double precision,
  main_index_today_pct double precision,
  smallcap_index_code text,
  smallcap_close double precision,
  smallcap_recent3_cum_pct double precision,
  premarket_regime text,
  premarket_reasons jsonb,
  a50_value_date date,
  a50_source text,
  a50_close double precision,
  a50_pct_chg double precision,
  vix_value_date date,
  vix_source text,
  vix_close double precision,
  vix_pct_chg double precision,
  benchmark_slot text,
  premarket_slot text,
  market_posture_code text,
  market_posture_name text,
  wind_phrase text,
  water_phrase text,
  action_phrase text,
  banner_tone text,
  banner_title text,
  banner_message text,
  source_jobs jsonb,
  updated_at timestamptz not null default now(),
  primary key (trade_date, market),
  constraint chk_market_signal_daily_market
    check (market in ('cn', 'us', 'hk'))
);

create index if not exists idx_market_signal_daily_market_trade_date
  on public.market_signal_daily (market, trade_date desc);


create table if not exists public.recommendation_tracking (
  id bigint generated by default as identity primary key,
  market text not null default 'cn',
  symbol text not null,
  code bigint,
  name text,
  recommend_reason text,
  recommend_date integer not null,
  initial_price double precision,
  current_price double precision,
  change_pct double precision,
  recommend_count integer not null default 1,
  funnel_score double precision,
  is_ai_recommended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_recommendation_tracking_market
    check (market in ('cn', 'us')),
  constraint uq_recommendation_tracking_market_symbol_date
    unique (market, symbol, recommend_date)
);

create index if not exists idx_recommendation_tracking_market_symbol
  on public.recommendation_tracking (market, symbol);

create index if not exists idx_recommendation_tracking_recommend_date
  on public.recommendation_tracking (recommend_date desc);


create table if not exists public.signal_pending (
  id bigint generated by default as identity primary key,
  code bigint not null,
  signal_type text not null,
  signal_date date not null,
  signal_score double precision,
  status text not null default 'pending',
  ttl_days integer not null default 3,
  days_elapsed integer not null default 0,
  regime text,
  name text,
  industry text,
  snap_open double precision,
  snap_high double precision,
  snap_low double precision,
  snap_close double precision,
  snap_volume double precision,
  snap_ma20 double precision,
  snap_ma50 double precision,
  snap_support double precision,
  confirm_reason text,
  confirm_date date,
  expire_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_signal_pending_status_signal_date
  on public.signal_pending (status, signal_date desc);

create unique index if not exists uq_signal_pending_active_code_type
  on public.signal_pending (code, signal_type)
  where status = 'pending';


create table if not exists public.index_constituents_snapshot (
  market text not null,
  index_code text not null,
  as_of text not null,
  symbols text[] not null default '{}',
  source text not null,
  raw_payload jsonb,
  updated_at timestamptz not null default now(),
  primary key (market, index_code),
  constraint chk_index_constituents_snapshot_market
    check (market in ('cn', 'us', 'hk'))
);


create table if not exists public.portfolios (
  portfolio_id text primary key,
  name text,
  free_cash double precision not null default 0,
  total_equity double precision,
  updated_at timestamptz not null default now()
);


create table if not exists public.portfolio_positions (
  portfolio_id text not null,
  market text not null default 'cn',
  code text not null,
  name text,
  shares integer not null default 0,
  cost_price double precision not null default 0,
  buy_dt text,
  strategy text,
  stop_loss double precision,
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, market, code),
  constraint chk_portfolio_positions_market
    check (market in ('cn', 'us'))
);

create index if not exists idx_portfolio_positions_portfolio_market
  on public.portfolio_positions (portfolio_id, market);


create table if not exists public.trade_orders (
  id bigint generated by default as identity primary key,
  run_id text not null,
  portfolio_id text not null,
  trade_date date not null,
  model text,
  market_view text,
  market text not null default 'cn',
  code text not null,
  name text,
  action text,
  status text,
  shares integer not null default 0,
  price_hint double precision,
  amount double precision not null default 0,
  stop_loss double precision,
  max_loss double precision not null default 0,
  drawdown_ratio double precision not null default 0,
  reason text,
  tape_condition text,
  invalidate_condition text,
  created_at timestamptz not null default now(),
  constraint chk_trade_orders_market
    check (market in ('cn', 'us'))
);

create index if not exists idx_trade_orders_portfolio_trade_date_market
  on public.trade_orders (portfolio_id, trade_date desc, market);

create index if not exists idx_trade_orders_run_id
  on public.trade_orders (run_id);


create table if not exists public.daily_nav (
  portfolio_id text not null,
  trade_date date not null,
  free_cash double precision not null default 0,
  positions_value double precision not null default 0,
  total_equity double precision not null default 0,
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, trade_date)
);

create index if not exists idx_daily_nav_trade_date
  on public.daily_nav (trade_date desc);

commit;

-- Intentionally omitted:
-- - user_settings
-- - job_usage
-- - user_tier
-- These are tied to the old self-service/auth model and are not required for
-- the current "self-use + daily analysis" PostgreSQL migration target.
